config/routes.rb
XindiRails::Application.routes.draw do

  mount Bootsy::Engine => '/bootsy', as: 'bootsy' # https://github.com/volmer/bootsy

  # application root

  root 'public/pages#index'

  # admin routes

  get 'admin' => 'admin/dashboard#index', as: 'admin_dashboard'

  get 'admin/articles' => 'admin/articles#index', as: 'admin_articles'
  get 'admin/articles/new' => 'admin/articles#new', as: 'admin_articles_new'
  get 'admin/articles/:id/edit' => 'admin/articles#edit', as: 'admin_articles_edit'
  post 'admin/articles' => 'admin/articles#create', as: 'admin_articles_create'
  patch 'admin/articles/:id' => 'admin/articles#update', as: 'admin_articles_update'
  delete 'admin/articles/:id' => 'admin/articles#destroy', as: 'admin_articles_destroy'

  get 'admin/enquiries' => 'admin/enquiries#index', as: 'admin_enquiries'
  get 'admin/enquiries/:id' => 'admin/enquiries#show', as: 'admin_enquiries_show'
  delete 'admin/enquiries/:id' => 'admin/enquiries#destroy', as: 'admin_enquiries_destroy'

  get 'admin/login' => 'admin/sessions#new', as: 'admin_login'
  post 'admin/login' => 'admin/sessions#create', as: 'admin_login_create'
  delete 'admin/logout' => 'admin/sessions#destroy', as: 'admin_logout'

  get 'admin/pages' => 'admin/pages#index', as: 'admin_pages'
  get 'admin/pages/new/:ancestor_id' => 'admin/pages#new', as: 'admin_pages_new'
  get 'admin/pages/:id/edit' => 'admin/pages#edit', as: 'admin_pages_edit'
  get 'admin/pages/move' => 'admin/pages#move', as: 'admin_pages_move'
  post 'admin/pages' => 'admin/pages#create', as: 'admin_pages_create'
  patch 'admin/pages/:id' => 'admin/pages#update', as: 'admin_pages_update'
  delete 'admin/pages/:id' => 'admin/pages#destroy', as: 'admin_pages_destroy'

  get 'admin/users' => 'admin/users#index', as: 'admin_users'
  get 'admin/users/new' => 'admin/users#new', as: 'admin_users_new'
  get 'admin/users/:id/edit' => 'admin/users#edit', as: 'admin_users_edit'
  post 'admin/users' => 'admin/users#create', as: 'admin_users_create'
  patch 'admin/users/:id' => 'admin/users#update', as: 'admin_users_update'
  delete 'admin/users/:id' => 'admin/users#destroy', as: 'admin_users_destroy'

  # public routes

  get 'contact' => 'public/enquiries#index', as: 'public_enquiries'
  post 'contact' => 'public/enquiries#create', as: 'public_enquiries_create'

  get 'search' => 'public/search#index', as: 'public_search'

  get 'news' => 'public/articles#index', as: 'public_articles'
  get 'news/:slug' => 'public/articles#show', as: 'public_articles_show'

  get ':slug' => 'public/pages#index'
  get ':slug/:child_slug' => 'public/pages#index'

end

app/views/admin/pages/index.html.erb
<% if @pages.count != 0 %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Title</th>
        <th>Published</th>
        <th>Last Updated</th>
        <th>Depth</th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @pages.each do |page| %>
        <tr>
          <td style="text-indent:<%= page.depth > 1 ? ((page.depth - 1) * 15) + 10 : 0 %>px"><%= page.title %></td>
          <td><%= format_date(page.created_at) %></td>
          <td><%= format_date(page.updated_at) %></td>
          <td><%= page.depth %></td>
          <td>
            <%= link_to_if page.can_move_up?, content_tag(:div, '', :class => "glyphicon glyphicon-chevron-up"), { controller: 'admin/pages', action: 'move', id: page.id, direction: 'up' }, title: 'Move Up' do %>
              <i class="glyphicon glyphicon-chevron-up"></i>
            <% end %>
          </td>
          <td>
            <%= link_to_if page.can_move_down?, content_tag(:div, '', :class => "glyphicon glyphicon-chevron-down"), { controller: 'admin/pages', action: 'move', id: page.id, direction: 'down' }, title: 'Move Down' do %>
              <i class="glyphicon glyphicon-chevron-down"></i>
            <% end %>
          </td>
          <td>
            <%= link_to_if page.can_add_page?, content_tag(:div, '', :class => "glyphicon glyphicon-plus"), { controller: 'admin/pages', action: 'new', ancestor_id: page.id }, title: 'Add Page' do %>
              <i class="glyphicon glyphicon-plus"></i>
            <% end %>
          </td>
          <td>
            <%= link_to admin_pages_edit_path(page), title: 'Edit' do %>
              <i class="glyphicon glyphicon-pencil"></i>
            <% end %>
          </td>
          <td>
            <%= link_to_if page.can_delete_page?, content_tag(:div, '', :class => "glyphicon glyphicon-remove"), admin_pages_destroy_path(page), method: :delete, data: { confirm: 'Are you sure?' }, title: 'Delete' do %>
              <i class="glyphicon glyphicon-remove"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>There are currently no pages.</p>
<% end %>

app/views/admin/pages/maintain.html.erb
<%= form_for @page, url: {action: @action} do |f| %>
  <% if @page.errors.any? %>
    <div class="alert alert-danger">
      <p>Please amend the following <%= pluralize(@page.errors.count, 'field') %>:</p>

      <ul>
        <% @page.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, :class => 'form-control', :maxlength => '150', :required => true %>
  </div>

  <div class="form-group">
    <%= f.label :content %>
    <%= f.bootsy_area :content, cols: 20, rows: 20, :class => 'form-control', :required => true %>
  </div>

  <div class="checkbox">
    <%= f.label :meta_generated, :class => 'checkbox inline' do %>
      <%= f.check_box :meta_generated %>
      Generate automatically
    <% end %>
  </div>

  <div class="form-group">
    <%= f.label :meta_title %>
    <%= f.text_field :meta_title, :class => 'form-control', :maxlength => '200' %>
  </div>

  <div class="form-group">
    <%= f.label :meta_description %>
    <%= f.text_field :meta_description, :class => 'form-control', :maxlength => '200' %>
  </div>

  <div class="form-group">
    <%= f.label :meta_keywords %>
    <%= f.text_field :meta_keywords, :class => 'form-control', :maxlength => '200' %>
  </div>

  <%= f.submit 'Save Page', :class => 'btn btn-default' %>
  <%= link_to 'Cancel', admin_pages_path, class: 'btn cancel' %>

  <%= f.hidden_field :ancestor_id %>
<% end %>