config/routes.rb
XindiRails::Application.routes.draw do

  mount Bootsy::Engine => '/bootsy', as: 'bootsy' # https://github.com/volmer/bootsy

  # application root

  root 'public/pages#index'

  # admin routes

  get 'admin' => 'admin/dashboard#index', as: 'admin_dashboard'

  get 'admin/articles' => 'admin/articles#index', as: 'admin_articles'
  get 'admin/articles/new' => 'admin/articles#new', as: 'admin_articles_new'
  get 'admin/articles/:id/edit' => 'admin/articles#edit', as: 'admin_articles_edit'
  post 'admin/articles' => 'admin/articles#create', as: 'admin_articles_create'
  patch 'admin/articles/:id' => 'admin/articles#update', as: 'admin_articles_update'
  delete 'admin/articles/:id' => 'admin/articles#destroy', as: 'admin_articles_destroy'

  get 'admin/enquiries' => 'admin/enquiries#index', as: 'admin_enquiries'
  get 'admin/enquiries/:id' => 'admin/enquiries#show', as: 'admin_enquiries_show'
  delete 'admin/enquiries/:id' => 'admin/enquiries#destroy', as: 'admin_enquiries_destroy'

  get 'admin/login' => 'admin/sessions#new', as: 'admin_login'
  post 'admin/login' => 'admin/sessions#create', as: 'admin_login_create'
  delete 'admin/logout' => 'admin/sessions#destroy', as: 'admin_logout'

  get 'admin/pages' => 'admin/pages#index', as: 'admin_pages'
  get 'admin/pages/new/:ancestor_id' => 'admin/pages#new', as: 'admin_pages_new'
  get 'admin/pages/:id/edit' => 'admin/pages#edit', as: 'admin_pages_edit'
  get 'admin/pages/move' => 'admin/pages#move', as: 'admin_pages_move'
  post 'admin/pages' => 'admin/pages#create', as: 'admin_pages_create'
  patch 'admin/pages/:id' => 'admin/pages#update', as: 'admin_pages_update'
  delete 'admin/pages/:id' => 'admin/pages#destroy', as: 'admin_pages_destroy'

  get 'admin/users' => 'admin/users#index', as: 'admin_users'
  get 'admin/users/new' => 'admin/users#new', as: 'admin_users_new'
  get 'admin/users/:id/edit' => 'admin/users#edit', as: 'admin_users_edit'
  post 'admin/users' => 'admin/users#create', as: 'admin_users_create'
  patch 'admin/users/:id' => 'admin/users#update', as: 'admin_users_update'
  delete 'admin/users/:id' => 'admin/users#destroy', as: 'admin_users_destroy'

  # public routes

  get 'contact' => 'public/enquiries#index', as: 'public_enquiries'
  post 'contact' => 'public/enquiries#create', as: 'public_enquiries_create'

  get 'search' => 'public/search#index', as: 'public_search'

  get 'news' => 'public/articles#index', as: 'public_articles'
  get 'news/:slug' => 'public/articles#show', as: 'public_articles_show'

  get ':slug' => 'public/pages#index'
  get ':slug/:child_slug' => 'public/pages#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  include Bootsy::Container
  include MetaData

  validates :title, :content, :author, presence: true
  validates :title, uniqueness: true

  before_create :set_unique_slug

  def get_url(url)
    url << "/" << self.slug
  end

  private

    def set_unique_slug
      slug = self.title.to_s.gsub(/[^0-9A-Za-z]/, '-').downcase
      while Article.where(slug: slug).count > 0 do
        slug << '-'
      end
      self.slug = slug
    end

end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < Admin::BaseController
  before_action :set_article, only: [:edit, :update, :destroy]

  # GET /admin/articles
  def index
    @page_title = 'News'
    @articles = Article.order('created_at DESC')
  end

  # GET /admin/articles/new
  def new
    @page_title = 'Add Article'
    @article = Article.new
    @action = 'create'
    render :template => 'admin/articles/maintain'
  end

  # GET /admin/articles/:id/edit
  def edit
    @page_title = 'Edit Article'
    @action = 'update'
    render :template => 'admin/articles/maintain'
  end

  # POST /admin/articles
  def create
    @article = Article.new(article_params)

    if @article.save
      flash[:success] = 'The article was successfully created.'
      redirect_to admin_articles_path
    else
      @page_title = 'Add Article'
      render action: 'maintain'
    end
  end

  # PATCH /admin/articles/:id
  def update
    if @article.update(article_params)
      flash[:success] = 'The article was successfully updated.'
      redirect_to admin_articles_path
    else
      @page_title = 'Edit Article'
      render action: 'maintain'
    end
  end

  # DELETE /admin/articles/:id
  def destroy
    @article.destroy
    flash[:success] = 'The article was successfully deleted.'
    redirect_to admin_articles_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:slug, :title, :content, :meta_generated, :meta_title, :meta_description, :meta_keywords, :author, :bootsy_image_gallery_id)
    end
end

app/views/admin/articles/index.html.erb
<p class="pull-right">
  <%= link_to admin_articles_new_path, class: 'btn btn-primary' do %>
    Add Article <i class="glyphicon glyphicon-plus glyphicon-white"></i>
  <% end %>
</p>

<% if @articles.count != 0 %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Title</th>
        <th>Published</th>
        <th>Last Updated</th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @articles.each do |article| %>
        <tr>
          <td><%= article.title %></td>
          <td><%= format_date(article.created_at) %></td>
          <td><%= format_date(article.updated_at) %></td>
          <td>
            <%= link_to admin_articles_edit_path(article), title: 'Edit' do %>
              <i class="glyphicon glyphicon-pencil"></i>
            <% end %>
          </td>
          <td>
            <%= link_to admin_articles_destroy_path(article), method: :delete, data: { confirm: 'Are you sure?' }, title: 'Delete' do %>
              <i class="glyphicon glyphicon-remove"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>There are currently no news stories.</p>
<% end %>

app/views/admin/articles/maintain.html.erb
<%= form_for @article, url: {action: @action} do |f| %>
  <% if @article.errors.any? %>
    <div class="alert alert-danger">
      <p>Please amend the following <%= pluralize(@article.errors.count, 'field') %>:</p>

      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, :class => 'form-control', :maxlength => '150', :required => true %>
  </div>

  <div class="form-group">
    <%= f.label :content %>
    <%= f.bootsy_area :content, cols: 20, rows: 20, :class => 'form-control', :required => true %>
  </div>

  <div class="checkbox">
    <%= f.label :meta_generated, :class => 'checkbox inline' do %>
      <%= f.check_box :meta_generated %>
      Generate automatically
    <% end %>
  </div>

  <div class="form-group">
    <%= f.label :meta_title %>
    <%= f.text_field :meta_title, :class => 'form-control', :maxlength => '200' %>
  </div>

  <div class="form-group">
    <%= f.label :meta_description %>
    <%= f.text_field :meta_description, :class => 'form-control', :maxlength => '200' %>
  </div>

  <div class="form-group">
    <%= f.label :meta_keywords %>
    <%= f.text_field :meta_keywords, :class => 'form-control', :maxlength => '200' %>
  </div>

  <div class="form-group">
    <%= f.label :author %>
    <%= f.text_field :author, :class => 'form-control', :maxlength => '100', :required => true %>
  </div>

  <%= f.submit nil, :class => 'btn btn-default' %>
  <%= link_to 'Cancel', admin_articles_path, class: 'btn cancel' %>
<% end %>