config/routes.rb
XindiRails::Application.routes.draw do

  mount Bootsy::Engine => '/bootsy', as: 'bootsy' # https://github.com/volmer/bootsy

  # application root

  root 'public/pages#index'

  # admin routes

  get 'admin' => 'admin/dashboard#index', as: 'admin_dashboard'

  get 'admin/articles' => 'admin/articles#index', as: 'admin_articles'
  get 'admin/articles/new' => 'admin/articles#new', as: 'admin_articles_new'
  get 'admin/articles/:id/edit' => 'admin/articles#edit', as: 'admin_articles_edit'
  post 'admin/articles' => 'admin/articles#create', as: 'admin_articles_create'
  patch 'admin/articles/:id' => 'admin/articles#update', as: 'admin_articles_update'
  delete 'admin/articles/:id' => 'admin/articles#destroy', as: 'admin_articles_destroy'

  get 'admin/enquiries' => 'admin/enquiries#index', as: 'admin_enquiries'
  get 'admin/enquiries/:id' => 'admin/enquiries#show', as: 'admin_enquiries_show'
  delete 'admin/enquiries/:id' => 'admin/enquiries#destroy', as: 'admin_enquiries_destroy'

  get 'admin/login' => 'admin/sessions#new', as: 'admin_login'
  post 'admin/login' => 'admin/sessions#create', as: 'admin_login_create'
  delete 'admin/logout' => 'admin/sessions#destroy', as: 'admin_logout'

  get 'admin/pages' => 'admin/pages#index', as: 'admin_pages'
  get 'admin/pages/new/:ancestor_id' => 'admin/pages#new', as: 'admin_pages_new'
  get 'admin/pages/:id/edit' => 'admin/pages#edit', as: 'admin_pages_edit'
  get 'admin/pages/move' => 'admin/pages#move', as: 'admin_pages_move'
  post 'admin/pages' => 'admin/pages#create', as: 'admin_pages_create'
  patch 'admin/pages/:id' => 'admin/pages#update', as: 'admin_pages_update'
  delete 'admin/pages/:id' => 'admin/pages#destroy', as: 'admin_pages_destroy'

  get 'admin/users' => 'admin/users#index', as: 'admin_users'
  get 'admin/users/new' => 'admin/users#new', as: 'admin_users_new'
  get 'admin/users/:id/edit' => 'admin/users#edit', as: 'admin_users_edit'
  post 'admin/users' => 'admin/users#create', as: 'admin_users_create'
  patch 'admin/users/:id' => 'admin/users#update', as: 'admin_users_update'
  delete 'admin/users/:id' => 'admin/users#destroy', as: 'admin_users_destroy'

  # public routes

  get 'contact' => 'public/enquiries#index', as: 'public_enquiries'
  post 'contact' => 'public/enquiries#create', as: 'public_enquiries_create'

  get 'search' => 'public/search#index', as: 'public_search'

  get 'news' => 'public/articles#index', as: 'public_articles'
  get 'news/:slug' => 'public/articles#show', as: 'public_articles_show'

  get ':slug' => 'public/pages#index'
  get ':slug/:child_slug' => 'public/pages#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email_address, presence: true, uniqueness: true
  validates_format_of :email_address, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  has_secure_password

  after_destroy :ensure_an_admin_remains

  private
    def ensure_an_admin_remains
      if User.count.zero?
        raise "Can't delete last user"
      end
    end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :set_user, only: [:edit, :update, :destroy]

  # GET /admin/users
  def index
    @page_title = 'Users'
    @users = User.order('created_at DESC')
  end

  # GET /admin/users/new
  def new
    @page_title = 'Add User'
    @user = User.new
    @action = 'create'
    render :template => 'admin/users/maintain'
  end

  # GET /admin/users/:id/edit
  def edit
    @page_title = 'Edit User'
    @action = 'update'
    render :template => 'admin/users/maintain'
  end

  # POST /admin/users
  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'The user was successfully created.'
      redirect_to admin_users_path
    else
      @page_title = 'Add User'
      render action: 'maintain'
    end
  end

  # PATCH /admin/users/:id
  def update
    if @user.update(user_params)
      flash[:success] = 'The user was successfully updated.'
      redirect_to admin_users_path
    else
      @page_title = 'Edit User'
      render action: 'maintain'
    end
  end

  # DELETE /admin/users/:id
  def destroy
    begin
      @user.destroy
      flash[:success] = 'The user was successfully deleted.'
    rescue StandardError => e
      flash[:danger] = e.message
    end
    redirect_to admin_users_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email_address, :password, :password_confirmation)
    end
end

app/views/admin/users/index.html.erb
<p class="pull-right">
  <%= link_to admin_users_new_path, class: 'btn btn-primary' do %>
    Add User <i class="glyphicon glyphicon-plus glyphicon-white"></i>
  <% end %>
</p>

<% if @users.count != 0 %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Email</th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.email_address %></td>
          <td>
            <%= link_to admin_users_edit_path(user), title: 'Edit' do %>
              <i class="glyphicon glyphicon-pencil"></i>
            <% end %>
          </td>
          <td>
            <%= link_to admin_users_destroy_path(user), method: :delete, data: { confirm: 'Are you sure?' }, title: 'Delete' do %>
              <i class="glyphicon glyphicon-remove"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>There are currently no users.</p>
<% end %>

app/views/admin/users/maintain.html.erb
<%= form_for @user, url: {action: @action} do |f| %>
  <% if @user.errors.any? %>
    <div class="alert alert-danger">
      <p>Please amend the following <%= pluralize(@user.errors.count, 'field') %>:</p>

      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :email_address %>
    <%= f.text_field :email_address, :class => 'form-control', :maxlength => '100', :required => true, :pattern => '[^@]+@[^@]+\.[a-zA-Z]{2,6}' %>
  </div>

  <div class="form-group">
    <%= f.label :password %>
    <%= f.text_field :password, :class => 'form-control', :required => true %>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation, 'Confirm Password' %>
    <%= f.text_field :password_confirmation, :class => 'form-control', :required => true %>
  </div>

  <%= f.submit 'Save User', :class => 'btn btn-default' %>
  <%= link_to 'Cancel', admin_users_path, class: 'btn cancel' %>
<% end %>