config/routes.rb
XindiRails::Application.routes.draw do

  mount Bootsy::Engine => '/bootsy', as: 'bootsy' # https://github.com/volmer/bootsy

  # application root

  root 'public/pages#index'

  # admin routes

  get 'admin' => 'admin/dashboard#index', as: 'admin_dashboard'

  get 'admin/articles' => 'admin/articles#index', as: 'admin_articles'
  get 'admin/articles/new' => 'admin/articles#new', as: 'admin_articles_new'
  get 'admin/articles/:id/edit' => 'admin/articles#edit', as: 'admin_articles_edit'
  post 'admin/articles' => 'admin/articles#create', as: 'admin_articles_create'
  patch 'admin/articles/:id' => 'admin/articles#update', as: 'admin_articles_update'
  delete 'admin/articles/:id' => 'admin/articles#destroy', as: 'admin_articles_destroy'

  get 'admin/enquiries' => 'admin/enquiries#index', as: 'admin_enquiries'
  get 'admin/enquiries/:id' => 'admin/enquiries#show', as: 'admin_enquiries_show'
  delete 'admin/enquiries/:id' => 'admin/enquiries#destroy', as: 'admin_enquiries_destroy'

  get 'admin/login' => 'admin/sessions#new', as: 'admin_login'
  post 'admin/login' => 'admin/sessions#create', as: 'admin_login_create'
  delete 'admin/logout' => 'admin/sessions#destroy', as: 'admin_logout'

  get 'admin/pages' => 'admin/pages#index', as: 'admin_pages'
  get 'admin/pages/new/:ancestor_id' => 'admin/pages#new', as: 'admin_pages_new'
  get 'admin/pages/:id/edit' => 'admin/pages#edit', as: 'admin_pages_edit'
  get 'admin/pages/move' => 'admin/pages#move', as: 'admin_pages_move'
  post 'admin/pages' => 'admin/pages#create', as: 'admin_pages_create'
  patch 'admin/pages/:id' => 'admin/pages#update', as: 'admin_pages_update'
  delete 'admin/pages/:id' => 'admin/pages#destroy', as: 'admin_pages_destroy'

  get 'admin/users' => 'admin/users#index', as: 'admin_users'
  get 'admin/users/new' => 'admin/users#new', as: 'admin_users_new'
  get 'admin/users/:id/edit' => 'admin/users#edit', as: 'admin_users_edit'
  post 'admin/users' => 'admin/users#create', as: 'admin_users_create'
  patch 'admin/users/:id' => 'admin/users#update', as: 'admin_users_update'
  delete 'admin/users/:id' => 'admin/users#destroy', as: 'admin_users_destroy'

  # public routes

  get 'contact' => 'public/enquiries#index', as: 'public_enquiries'
  post 'contact' => 'public/enquiries#create', as: 'public_enquiries_create'

  get 'search' => 'public/search#index', as: 'public_search'

  get 'news' => 'public/articles#index', as: 'public_articles'
  get 'news/:slug' => 'public/articles#show', as: 'public_articles_show'

  get ':slug' => 'public/pages#index'
  get ':slug/:child_slug' => 'public/pages#index'

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Xindi Rails</title>

    <%= stylesheet_link_tag "admin", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "admin", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <% if Rails.env == "development" %>
      <span class="dev-env label label-warning">Development Mode</span>
    <% end %>

    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

          <%= link_to image_tag('/assets/images/admin/xindi-logo.png', alt: 'Xindi logo'), admin_dashboard_path, class: 'brand' %>
        </div>

        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <% if session[:user_id] %>
              <li><%= link_to("Home", admin_dashboard_path) %></li>
              <li><%= link_to 'Pages', admin_pages_path %></li>
              <li><%= link_to 'News', admin_articles_path %></li>
              <li><%= link_to 'Enquiries', admin_enquiries_path %></li>
              <li><%= link_to 'Users', admin_users_path %></li>
              <li><%= link_to 'Logout', admin_logout_path, method: :delete %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container main-content">
      <h1><%= @page_title %></h1>

      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, class: 'alert alert-' + name.to_s() %>
      <% end %>

      <%= yield %>
    </div>

    <% if session[:user_id] %>
      <div class="footer" role="contentinfo">
        <div class="container">
          <p>
            Version <%= Rails.configuration.xindi[:version] %>
            <a href="#" id="top-of-page" class="pull-right">Back to top <i class="glyphicon glyphicon-chevron-up"></i></a>
          </p>
        </div>
      </div>
    <% end %>
  </body>
</html>

app/views/layouts/public.html.erb
<!DOCTYPE html>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= render '/public/shared/meta_data' %>

    <%= stylesheet_link_tag "public", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "public", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>

    <%= yield :head %>
  </head>

  <body>
    <% if Rails.env == "development" %>
      <span class="dev-env label label-warning">Development Mode</span>
    <% end %>

    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

          <%= link_to image_tag('/assets/images/public/xindi-logo.png', alt: 'Site logo'), root_path, class: 'brand' %>
        </div>

        <div id="navbar">
          <%= get_navigation.html_safe %>

          <%= form_tag(public_search_path, method: 'get', class: 'navbar-form navbar-right') do %>
            <div class="form-group">
              <%= text_field_tag(:search_term, nil, class: 'form-control', placeholder: 'Search') %>
            </div>
            <%= submit_tag('Search', class: 'btn btn-default') %>
          <% end %>
        </div>
      </div>
    </nav>

    <div class="container main-content">
      <%= yield %>
    </div>
  </body>
</html>